name: Transporter
main: org.bennedum.transporter.Transporter
version: 6.7
authors:
  - frdfsnlght
website: something@code.google.com
description: >
  Provides teleportation through gates between worlds and servers.
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /trp command [<option> ...]

