name: Transporter
main: org.bennedum.transporter.Transporter
version: "7.2"
authors:
  - frdfsnlght
website: http://code.google.com/p/bukkit-transporter/
description: >
  Provides teleportation through gates between worlds and servers.
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]

