name: Transporter
main: org.bennedum.transporter.Transporter
version: "7.8"
authors:
  - frdfsnlght
website: http://dev.bukkit.org/server-mods/transporter/
description: >
  Provides teleportation through gates between worlds and servers.
commands:
  trp:
    description: Main Transporter command. See /trp help for more.
    usage: /<command> command [<option> ...]

